### ISSUE TITLE
About  BodyPoseEstimator

### ISSUE THREAD

**Issue by yangfeixia88** [prasunroy/pose-transfer#2]
Thank your great job. But I don't know about BodyPoseEstimator.
![image](https://user-images.githubusercontent.com/86911875/160827253-0a85b0b1-1c62-4c92-a048-2317c6512a43.png)

**Comment by prasunroy** [comment]
Thanks! You need to install the OpenPose API wrapper for this.
```
pip install git+https://github.com/prasunroy/openpose-pytorch.git
```

For more information check https://github.com/prasunroy/openpose-pytorch.

**Comment by yangfeixia88** [comment]
Thank you for your answer,But I have one more question,How do you train and test?
![image](https://user-images.githubusercontent.com/86911875/161001252-043a792e-1115-49f2-8428-834fa1862370.png)

**Comment by prasunroy** [comment]
If you are training from scratch then simply run `python train.py`. However, if you like to resume training from a previous checkpoint, then you can specify the existing directory containing the checkpoints and the respective checkpoint number.
For example, to resume training from the pretrained checkpoint at iteration 260500 modify lines 27-28 of `train.py` as follows:
```python
ckpt_id = 260500
ckpt_dir = f'../output/{dataset_name}/ckpt/pretrained'
```
Every run of `train.py` will create a new directory under `f'../output/{dataset_name}/ckpt/` for saving checkpoints for that run. The name of such a directory is the `run_id` for that specific run. This `run_id` will be used in both `test.py` and `eval.py` for testing and evaluation respectively.

During testing, you need to specify the `run_id` and `ckpt_ids` for a specific run.
For example, to test the pretrained checkpoints at iterations 257500 and 260500 modify lines 22-23 of `test.py` as follows:
```python
run_id = 'pretrained'
ckpt_ids = [257500, 260500]
```
Then simply run `python test.py`.

Similarly, during evaluation, you need to specify the `run_id` and `ckpt_ids` for a specific run. However, make sure to run `test.py` first to generate the images for the specific checkpoint(s) you wish to evaluate.
For example, to evaluate the pretrained checkpoint at iteration 257500 modify lines 19-20 of `eval.py` as follows:
```python
run_id = 'pretrained'
ckpt_ids = [257500]
```
Then simply run `python eval.py`

**Comment by yangfeixia88** [comment]
Thank you very much for your patient reply and your excellent work.
