### ISSUE TITLE
Experimental equipment

### ISSUE THREAD

**Issue by cskyy** [prasunroy/pose-transfer#5]
I would like to know what experimental equipment you used. The model I retrained using RTX3090 for testing did not reach the effect of the pre-trained model you gave.

**Comment by prasunroy** [comment]
We trained the network on a single NVIDIA TITAN X GPU (12 GB VRAM) for 270K iterations with a batch size of 8 and serialized the network weights after every 500 iterations. We select the checkpoint with best evaluation metrics during inference among the 70 most recent checkpoints. RTX 3090 has 24 GB VRAM and much faster cores. You should be able to speed up the process with a larger batch size. You can specify the training configuration by editing `lines 12 - 31` in `train.py`.

**Comment by cskyy** [comment]
> 

Thank you for your reply. I will try again according to your suggestion.

**Comment by cskyy** [comment]
> 我们在单个 NVIDIA TITAN X GPU（12 GB VRAM）上训练网络进行 270K 迭代，批大小为 8，并在每 500 次迭代后序列化网络权重。我们在推理过程中从 70 个最新检查点中选择具有最佳评估指标的检查点。RTX 3090具有24 GB VRAM和更快的内核。您应该能够以更大的批量大小加快该过程。您可以通过在 中编辑来指定训练配置。`lines 12 - 31``train.py`

I'm sorry to bother you again, but I was wondering, have you tried to do the experiment at a higher resolution?

**Comment by prasunroy** [comment]
No. All experiments were performed at 256x256 resolution.
